# Generated by Django 5.0.6 on 2024-06-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ciclo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='foro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='valoracion',
            options={'managed': True},
        ),
    ]
